# This is a basic workflow to help you get started with Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    tags:
    - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: mark-hartmann/mstp-master
          event-type: new-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - run: echo hello
